// src/context/constants.js
export const reducerCases = {
  SET_USER_INFO: "SET_USER_INFO",
  SET_NEW_USER: "SET_NEW_USER",
  SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
  CHANGE_CURRENT_CHAT_USER: "CHANGE_CURRENT_CHAT_USER",


  SET_CURRENT_GROUP: "SET_CURRENT_GROUP",

  SET_MESSAGES: "SET_MESSAGES",
  SET_SOCKET: "SET_SOCKET",
  ADD_MESSAGE: "ADD_MESSAGE",
  SET_MESSAGE_SEARCH: "SET_MESSAGE_SEARCH",
  SET_USER_CONTACTS: "SET_USER_CONTACTS",
  SET_ONLINE_USERS: "SET_ONLINE_USERS",
  SET_CONTACT_SEARCH: "SET_CONTACT_SEARCH",
  SET_VIDEO_CALL: "SET_VIDEO_CALL",
  SET_VOICE_CALL: "SET_VOICE_CALL",
  END_CALL: "END_CALL",

 
  SET_INCOMING_VIDEO_CALL: "SET_INCOMING_VIDEO_CALL",
  SET_INCOMING_VOICE_CALL: "SET_INCOMING_VOICE_CALL",

  SHOW_GROUP_FILES: "SHOW_GROUP_FILES",
  HIDE_GROUP_FILES: "HIDE_GROUP_FILES",

  SET_EXIT_CHAT: "SET_EXIT_CHAT",

  UPDATE_CONTACT_ROLE: "UPDATE_CONTACT_ROLE",
};
